# Configuration for Alacritty, the GPU enhanced terminal emulator.
#
# See https://raw.githubusercontent.com/alacritty/alacritty/master/alacritty.yml
# for the up-to-date configuration schema
import:
  # Default to gruvbox_dark theme
  - ~/.config/alacritty/gruvbox_dark.yaml
  # Make it possible to override the theme by creating a current_theme.yaml file
  - ~/.local/share/alacritty/clj_current_theme.yaml

# Font configuration
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # See here
    # https://github.com/alacritty/alacritty/commit/6b327b6f8f0f308ff8f46cdf551ce0d0f3eda60b
    # for how Alacritty selects fallback fonts
    #
    # Just use monospace family. I've configured as the system level the
    # font to use and the appropriate fallbacks.
    family: monospace
    style: Regular
  # Point size
  size: 12.0

mouse:
  hide_when_typing: true

