
[font]
size = 12.0

[font.normal]
family = "monospace"
style = "Regular"

[mouse]
hide_when_typing = true

[bell]
command = { program = "xkbbell" }

[general]
import = ["~/.config/alacritty/gruvbox_dark.toml", "~/.local/share/alacritty/clj_current_theme.toml"]
