keys:
  - &long_term_age_key age1dpz24ggg809nztfmckn8a30s3ctnpwdmfgphyf9rcw9p77a0gssqeqpp7q
creation_rules:
  - path_regex: src/nixos/users/lijun/secrets.yaml$
    key_groups:
      - age:
          - *long_term_age_key
          # WSL2
          - age14sgkhy79syhhsndj4nfdkd6syp40p8pkq0fx5egeeffq74cslgusmwg65y
          # IDP: gpu-01
          - age1nnv32q4lcxnajc909lwf2svv74e4rgclnk7qfs2szhjv48er3atq3f5lz6
          # IDP: cmp-01
          - age1ual7en8x25uk7vfg08mf7r39jfh00j53l66w2hapdehfxxacksasv95jed
