#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  colorscheme = 'gruvbox'
  background = 'dark'
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = true
  autocomplete_method = "coc"
  filemanager = "nerdtree"
  sidebar_direction = "left"
  snippet_engine = "ultisnips"
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  statusline_separator = 'arrow'
  statusline_inactive_separator = 'arrow'
  buffer_index_type = 4
  enable_tabline_filetype_icon = false
  enable_statusline_display_mode = false
  default_indent = 4
  expand_tab = 0
  bootstrap_before = "myspacevim#before"
  bootstrap_after = "myspacevim#after"
  disabled_plugins = ['tagbar', 'vim-startify', 'Clamp']
  debug_level = 3

[[custom_plugins]]
  name = "junegunn/vim-easy-align"
  on_cmd = ["EasyAlign"]

[[custom_plugins]]
  name = "reisub0/hot-reload.vim"

[[layers]]
  name = 'core#tabline'
  enable = false

[[layers]]
  name = 'checkers'
  enable = false

[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = 'complete'
  auto-completion-tab-key-behavior = 'smart'

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30

[[layers]]
  name = 'leaderf'

[[layers]]
  name = 'tools#zeal'

[[layers]]
  name = 'VersionControl'

[[layers]]
  name = 'git'

[[layers]]
  name = 'github'

[[layers]]
  name = 'tags'
  enable = false

[[layers]]
  name = "tmux"
  tmux_navigator_modifier = "alt"

[[layers]]
  name = 'sudo'

[[layers]]
  name = 'lang#c'

[[layers]]
  name = 'lang#cpp'

[[layers]]
  name = 'lang#latex'

[[layers]]
  name = 'lang#markdown'

[[layers]]
  name = 'lang#plantuml'

[[layers]]
  name = 'lang#sh'

[[layers]]
  name = 'lang#vim'

[[layers]]
  name = 'lang#html'

[[layers]]
  name = 'lang#dart'

[[layers]]
  name = 'lang#asciidoc'

[[layers]]
  name = 'lang#dockerfile'

[[layers]]
  name = 'lang#dockerfile'

[[layers]]
  name = 'lang#extra'

[[layers]]
  name = 'lsp'
  filetypes = [
    'c',
    'cpp',
    'dart'
  ]
  [layers.override_cmd]
    c = ['ccls', '--log-file=/tmp/ccls.log']
    cpp = ['ccls', '--log-file=/tmp/ccls.log']
