# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.kernel.sysctl = {
    # Allow the magic SysRq keys that I use
    # In particular "b" for reboot (128) and "f" to invoke OOM killer (64).
    # For now I don't really need 16 and 32 and they seem to have quite
    # widespread adoption.
    # See https://www.kernel.org/doc/html/latest/admin-guide/sysrq.html
    "kernel.sysrq" = 16 + 32 + 64 + 128;
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/addc027e-48f5-4c92-986b-6351c16dbbc1";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7374-9580";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
