# free output should be human readable
alias free='free -h'

# alias move and copy to be verbose and to prompt before overwriting
alias mv='mv -vi'
alias cp='cp -rvi'

# CMake has to always export the COMPILE_COMMANDS
alias cmake='cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1'

# Most frequenly used configuration for picocom
alias mypicocom='picocom -b 115200 --imap lfcrlf --omap crlf'

alias sudo='sudo '

function tmux
{
	local tmux_binary=$(which tmux)
	if [[ $# -gt 0 ]]; then
		$tmux_binary "$@"
	else
		$tmux_binary attach 2> /dev/null || $tmux_binary new -s misc
	fi
}
