# free output should be human readable
alias free='free -h'

# alias move and copy to be verbose and to prompt before overwriting
alias mv='mv -vi'
alias cp='cp -rvi'

# CMake has to always export the COMPILE_COMMANDS
alias cmake='cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1'

function tmux
{
	local tmux_binary=$(which tmux)
	if [[ $# -gt 0 ]]; then
		$tmux_binary "$@"
	else
		$tmux_binary attach 2> /dev/null || $tmux_binary new
	fi
}
