#
# See https://superuser.com/questions/187639/zsh-not-hitting-profile
#
emulate sh
. ~/.profile

# See https://realjenius.com/2020/01/12/kde-neon-snap-apps-missing/
emulate sh -c 'source /etc/profile'

emulate zsh
