" Generated by vim-plug
" Fri 31 Mar 2023 11:18:05 PM CEST
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['CamelCaseMotion'].commit = 'de439d7c06cffd0839a29045a103fe4b44b15cdc'
silent! let g:plugs['FastFold'].commit = 'ab3d199d288a51708c3181a25aba1f9de2050b89'
silent! let g:plugs['auto-pairs'].commit = '39f06b873a8449af8ff6a3eee716d3da14d63a76'
silent! let g:plugs['ctrlsf.vim'].commit = '32236a8b376d9311dec9b5fe795ca99d32060b13'
silent! let g:plugs['diffchar.vim'].commit = '3a90fa38c1d8d0421e61fca38665b769c36c81d5'
silent! let g:plugs['editorconfig-vim'].commit = '7f4e4dfc58c480d154116614e616d90aac77204d'
silent! let g:plugs['fugitive-gitlab.vim'].commit = 'b73a8e97de95d26280082abb7f51465a3d3b239e'
silent! let g:plugs['fzf'].commit = 'ae745d9397bdc8b91f3c1834def3b8ecb0ae57b1'
silent! let g:plugs['fzf.vim'].commit = 'dc71692255b62d1f67dc55c8e51ab1aa467b1d46'
silent! let g:plugs['goyo.vim'].commit = 'fa0263d456dd43f5926484d1c4c7022dfcb21ba9'
silent! let g:plugs['gruvbox'].commit = 'bf2885a95efdad7bd5e4794dd0213917770d79b7'
silent! let g:plugs['gv.vim'].commit = '320cc8c477c5acc4fa0e52a460d87b2af54fa051'
silent! let g:plugs['markdown-preview.nvim'].commit = '02cc3874738bc0f86e4b91f09b8a0ac88aef8e96'
silent! let g:plugs['nerdcommenter'].commit = 'd069f7fb562fb9eb6911fe23cda7aca2a387043e'
silent! let g:plugs['rainbow_parentheses.vim'].commit = '27e7cd73fec9d1162169180399ff8ea9fa28b003'
silent! let g:plugs['undotree'].commit = '485f01efde4e22cb1ce547b9e8c9238f36566f21'
silent! let g:plugs['vim-abolish'].commit = '7a05efb84e6068a0b0801d736b58fc645e5cdfd2'
silent! let g:plugs['vim-cool'].commit = '80536b9f2e23292708a64f2e7bcf5e596f9faf24'
silent! let g:plugs['vim-dispatch'].commit = '6cc2691576f97d43f8751664d1a1a908b99927e5'
silent! let g:plugs['vim-doge'].commit = '59c3e6c91259afa845ba9cb3eff0493406a498dd'
silent! let g:plugs['vim-easy-align'].commit = '12dd6316974f71ce333e360c0260b4e1f81169c3'
silent! let g:plugs['vim-fugitive'].commit = 'ef99f1d90cdb33a52931aed5868785b51fb9411d'
silent! let g:plugs['vim-localvimrc'].commit = '6cc9f9ffaaf44b45bd5268f8a541363619bf1b13'
silent! let g:plugs['vim-markdown-toc'].commit = '7ec05df27b4922830ace2246de36ac7e53bea1db'
silent! let g:plugs['vim-repeat'].commit = '24afe922e6a05891756ecf331f39a1f6743d3d5a'
silent! let g:plugs['vim-rhubarb'].commit = 'ee69335de176d9325267b0fd2597a22901d927b1'
silent! let g:plugs['vim-rooter'].commit = '4f52ca556a0b9e257bf920658714470ea0320b7a'
silent! let g:plugs['vim-sleuth'].commit = '1cc4557420f215d02c4d2645a748a816c220e99b'
silent! let g:plugs['vim-startify'].commit = '81e36c352a8deea54df5ec1e2f4348685569bed2'
silent! let g:plugs['vim-surround'].commit = '3d188ed2113431cf8dac77be61b842acb64433d9'
silent! let g:plugs['vim-table-mode'].commit = '9555a3e6e5bcf285ec181b7fc983eea90500feb4'
silent! let g:plugs['vimtex'].commit = '1043b590d98fa3f069a0879c65293aa2c7c31b0d'
silent! let g:plugs['zeavim.vim'].commit = '298e52ad683680b4aa19b53d009cf0e6b9197664'

PlugUpdate!

