" Generated by vim-plug
" Sun 15 Oct 2023 09:51:46 PM CEST
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['CamelCaseMotion'].commit = 'de439d7c06cffd0839a29045a103fe4b44b15cdc'
silent! let g:plugs['FastFold'].commit = 'ab3d199d288a51708c3181a25aba1f9de2050b89'
silent! let g:plugs['auto-pairs'].commit = '39f06b873a8449af8ff6a3eee716d3da14d63a76'
silent! let g:plugs['ctrlsf.vim'].commit = '32236a8b376d9311dec9b5fe795ca99d32060b13'
silent! let g:plugs['diffchar.vim'].commit = '0187321b741b58b67679f24b3151663319558c8f'
silent! let g:plugs['fugitive-gitlab.vim'].commit = '55fed481c0309b3405dd3d72921d687bf36873a8'
silent! let g:plugs['fzf'].commit = '3666448ca649093f6f6b534b67e5a8b865d11a00'
silent! let g:plugs['fzf.vim'].commit = 'd1016dbd7cec2d2a3bb5863776c84b4034e4b85e'
silent! let g:plugs['goyo.vim'].commit = 'fa0263d456dd43f5926484d1c4c7022dfcb21ba9'
silent! let g:plugs['gruvbox'].commit = 'f1ecde848f0cdba877acb0c740320568252cc482'
silent! let g:plugs['gv.vim'].commit = '320cc8c477c5acc4fa0e52a460d87b2af54fa051'
silent! let g:plugs['markdown-preview.nvim'].commit = '0b3830246367c11f27cd1fe75c19528bdfe00214'
silent! let g:plugs['nerdcommenter'].commit = 'd2e21d417f6c788b11ae3b90d7ac478930dead36'
silent! let g:plugs['rainbow_parentheses.vim'].commit = '27e7cd73fec9d1162169180399ff8ea9fa28b003'
silent! let g:plugs['undotree'].commit = '0e11ba7325efbbb3f3bebe06213afa3e7ec75131'
silent! let g:plugs['vim-abolish'].commit = 'dcbfe065297d31823561ba787f51056c147aa682'
silent! let g:plugs['vim-cool'].commit = '662e7b11064cbeedad17c45d2fe926e78d3cd0b6'
silent! let g:plugs['vim-dispatch'].commit = '6cc2691576f97d43f8751664d1a1a908b99927e5'
silent! let g:plugs['vim-doge'].commit = '3c9bb776c9c554bf6c32a12ab2b09d1bc17b702e'
silent! let g:plugs['vim-easy-align'].commit = '12dd6316974f71ce333e360c0260b4e1f81169c3'
silent! let g:plugs['vim-fugitive'].commit = 'cbe9dfa162c178946afa689dd3f42d4ea8bf89c1'
silent! let g:plugs['vim-localvimrc'].commit = 'ebb73832e6795967e5a52db3636a37282871b218'
silent! let g:plugs['vim-markdown-toc'].commit = '7ec05df27b4922830ace2246de36ac7e53bea1db'
silent! let g:plugs['vim-plugin-AnsiEsc'].commit = '690f820d20b6e3a79ba20499874eb7333aa4ca5c'
silent! let g:plugs['vim-repeat'].commit = '24afe922e6a05891756ecf331f39a1f6743d3d5a'
silent! let g:plugs['vim-rhubarb'].commit = 'ee69335de176d9325267b0fd2597a22901d927b1'
silent! let g:plugs['vim-rooter'].commit = '1353fa47ee3a81083c284e28ff4f7d92655d7c9e'
silent! let g:plugs['vim-sleuth'].commit = '1cc4557420f215d02c4d2645a748a816c220e99b'
silent! let g:plugs['vim-startify'].commit = '4e089dffdad46f3f5593f34362d530e8fe823dcf'
silent! let g:plugs['vim-surround'].commit = '3d188ed2113431cf8dac77be61b842acb64433d9'
silent! let g:plugs['vim-table-mode'].commit = '9555a3e6e5bcf285ec181b7fc983eea90500feb4'
silent! let g:plugs['vimtex'].commit = 'cbb20643b7bfe721902dac5760bf0d4889fb5f7e'
silent! let g:plugs['zeavim.vim'].commit = '298e52ad683680b4aa19b53d009cf0e6b9197664'

PlugUpdate!

