" Generated by vim-plug
" Fri 10 Jan 2025 12:18:52 PM CET
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['CamelCaseMotion'].commit = 'de439d7c06cffd0839a29045a103fe4b44b15cdc'
silent! let g:plugs['FastFold'].commit = 'fff6d05064dec4d7e1398aa507db35fcd57edfb4'
silent! let g:plugs['ctrlsf.vim'].commit = '32236a8b376d9311dec9b5fe795ca99d32060b13'
silent! let g:plugs['d2-vim'].commit = '981c87dccb63df2887cc41b96e84bf550f736c57'
silent! let g:plugs['diffchar.vim'].commit = 'ccf4c238a71d834ad1e21834f08be274bc0f05a3'
silent! let g:plugs['fugitive-gitlab.vim'].commit = '3584cf7e607ba7822f991d407a8d780e05aae287'
silent! let g:plugs['fzf'].commit = '14ef8e80519987962008b2da0c95907993d03865'
silent! let g:plugs['fzf.vim'].commit = '556f45e79ae5e3970054fee4c4373472604a1b4e'
silent! let g:plugs['goyo.vim'].commit = 'fa0263d456dd43f5926484d1c4c7022dfcb21ba9'
silent! let g:plugs['ical.vim'].commit = 'fc04e718533af6c7f920a7a908016f83addb53c8'
silent! let g:plugs['markdown-preview.nvim'].commit = 'a923f5fc5ba36a3b17e289dc35dc17f66d0548ee'
silent! let g:plugs['nerdcommenter'].commit = '66c07e4083ab02ed2540ac289cc602c70b858c13'
silent! let g:plugs['plantuml-syntax'].commit = '9d4900aa16674bf5bb8296a72b975317d573b547'
silent! let g:plugs['rainbow_parentheses.vim'].commit = '27e7cd73fec9d1162169180399ff8ea9fa28b003'
silent! let g:plugs['undotree'].commit = '2556c6800b210b2096b55b66e74b4cc1d9ebbe4f'
silent! let g:plugs['vim-abolish'].commit = 'dcbfe065297d31823561ba787f51056c147aa682'
silent! let g:plugs['vim-cool'].commit = '662e7b11064cbeedad17c45d2fe926e78d3cd0b6'
silent! let g:plugs['vim-dispatch'].commit = 'a2ff28abdb2d89725192db5b8562977d392a4d3f'
silent! let g:plugs['vim-easy-align'].commit = '9815a55dbcd817784458df7a18acacc6f82b1241'
silent! let g:plugs['vim-flog'].commit = '74e52ba4de25eb5f03824d65087750636d795641'
silent! let g:plugs['vim-fugitive'].commit = '174230d6a7f2df94705a7ffd8d5413e27ec10a80'
silent! let g:plugs['vim-markdown-toc'].commit = 'aa9cc3b07791db5cbe5f29d661763bc0eb4fb7c1'
silent! let g:plugs['vim-plugin-AnsiEsc'].commit = '690f820d20b6e3a79ba20499874eb7333aa4ca5c'
silent! let g:plugs['vim-repeat'].commit = '65846025c15494983dafe5e3b46c8f88ab2e9635'
silent! let g:plugs['vim-rhubarb'].commit = 'ee69335de176d9325267b0fd2597a22901d927b1'
silent! let g:plugs['vim-rooter'].commit = '51402fb77c4d6ae94994e37dc7ca13bec8f4afcc'
silent! let g:plugs['vim-sleuth'].commit = 'be69bff86754b1aa5adcbb527d7fcd1635a84080'
silent! let g:plugs['vim-startify'].commit = '4e089dffdad46f3f5593f34362d530e8fe823dcf'
silent! let g:plugs['vim-surround'].commit = '3d188ed2113431cf8dac77be61b842acb64433d9'
silent! let g:plugs['vim-table-mode'].commit = 'e4365bde024f73e205eefa2fb78e3029ddb92ea9'
silent! let g:plugs['vimtex'].commit = 'adce3d38349925a0a891857c74bd4e8d1b8f80ab'
silent! let g:plugs['zeavim.vim'].commit = '298e52ad683680b4aa19b53d009cf0e6b9197664'

PlugUpdate!

